# For more info on HTTP files go to https://aka.ms/vs/httpfile
@WebHost = http://localhost:5238
@userId = 3

# User 1:
#  PartsSilo: 1,2
#  PartType: only OEM
#  BaesVehicleId:Toyota VehicleID: 101,104

# User 2:
#  BaesVehicleId:Ford VehicleIds: 102, 105

# User 3:
# AdminUser: No Entitlements

### Get Vehicle
GET {{WebHost}}/admin/vehicle/102
X-User-Id: {{userId}} 


### Get Parts
GET {{WebHost}}/admin/parts
Content-Type: application/json
X-User-Id: {{userId}} 

{
  "vehicleId" : null,
  "contentSiloIds": ["1","2"],
  "TaxonomyId": "1",
  "vehicleMake": "Toyota",
  "VehicleYear": "2020"
}