@WebHost = http://localhost:5238

  ### Create Rule
POST {{WebHost}}/rules
Content-Type: application/json

{
  "id": 5,
  "ruleName": "Parts Silo",
  "entitlementId": 2,
  "criteria": { 
    "items": [
      {
        "field": "input1.ContentSiloIds",
        "operator": "ListsEqual",
        "value": "1,2"
      },
      {
        "field": "input1.VehicleYear",
        "operator": "GreaterThan",
        "value": "2010"
      },
      {
        "field": "input1.VehicleYear",
        "operator": "LessThan",
        "value": "2020"
      },
      {
        "field": "input1.VehicleMake",
        "operator": "IN",
        "value": "Acura,Ford"
      },
      {
        "field": "input1.TaxonomyId",
        "operator": "IN",
        "value": "1,2"
      }
    ],
    "operator": "And"
  },
  "isActive": true,
  "Actions": {
    "OnFailure": {
      "Name": "PartsAction",
      "Context": {
        "entitlementId": 2,
        "ContentSiloIds": [
          1,
          2
        ],
        "VehicleMakes": [
          "Acura",
          "Ford"
        ],
        "TaxonomyIds": [
          1,
          2
        ]
      }
    },
    "OnSuccess": {
      "Name": "PartsAction",
      "Context": {
        "entitlementId": 2,
        "ContentSiloIds": [
          1,
          2
        ],
        "VehicleMakes": [
          "Acura",
          "Ford"
        ],
        "TaxonomyIds": [
          1,
          2
        ]
      }
    }
  }
}

### Update Rule
PUT {{WebHost}}/rules
Content-Type: application/json

{
  "id": 5,
  "ruleName": "Parts Silo",
  "entitlementId": 2,
  "criteria": { 
    "items": [
      {
        "field": "input1.ContentSiloIds",
        "operator": "ListsEqual",
        "value": "1,2"
      },
      {
        "field": "input1.VehicleYear",
        "operator": "GreaterThan",
        "value": "2010"
      },
      {
        "field": "input1.VehicleYear",
        "operator": "LessThan",
        "value": "2020"
      },
      {
        "field": "input1.VehicleMake",
        "operator": "IN",
        "value": "Toyota,Ford"
      },
      {
        "field": "input1.TaxonomyId",
        "operator": "IN",
        "value": "1,2"
      }
    ],
    "operator": "And"
  },
  "isActive": true,
  "Actions": {
    "OnFailure": {
      "Name": "PartsAction",
      "Context": {
        "entitlementId": 2,
        "ContentSiloIds": [
          1,
          2
        ],
        "VehicleMakes": [
          "Toyota",
          "Ford"
        ],
        "TaxonomyIds": [
          1,
          2
        ]
      }
    },
    "OnSuccess": {
      "Name": "PartsAction",
      "Context": {
        "entitlementId": 2,
        "ContentSiloIds": [
          1,
          2
        ],
        "VehicleMakes": [
          "Acura",
          "Ford"
        ],
        "TaxonomyIds": [
          1,
          2
        ]
      }
    }
  }
}

### Get Rule by ID
GET {{WebHost}}/rules/10

### Get All Rules
GET {{WebHost}}/rules

### Delete Rule
DELETE {{WebHost}}/rules/6