@WebHost = http://localhost:5238

  ### Create Rule
POST {{WebHost}}/rules
Content-Type: application/json

{
  "id": 3,
  "ruleName": "PartsForEstimatingRule",
  "entitlementId": 3,
  "criteria": {
    "operator": "Or"
  },
  "isActive": true,
  "Actions": {
    "OnSuccess": {
      "Name": "PartsForEstimatingAction",
      "Context": {
        "entitlementId": 3,
        "part1Allowed": "true",
        "part2Allowed": "false"
      }
    }
  }
}

### Update Rule
PUT {{WebHost}}/rules
Content-Type: application/json



### Get Rule by ID
GET {{WebHost}}/rules/10

### Get All Rules
GET {{WebHost}}/rules

### Delete Rule
DELETE {{WebHost}}/rules/6