# For more info on HTTP files go to https://aka.ms/vs/httpfile
@WebHost = http://localhost:5238
@userId = 4

### Get Vehicle
GET {{WebHost}}/admin/vehicle/1000
X-User-Id: {{userId}} 


### Get Parts for Estimating
GET {{WebHost}}/admin/partsForEstimating
X-User-Id: {{userId}} 

### Test ContentSilo Entitlement
GET {{WebHost}}/admin/contentSilo
Content-Type: application/json
X-User-Id: {{userId}}

{
  "contentSiloIds": [10,20],
  "TaxonomyId": 1,
  "vehicleMake": "Toyota",
  "VehicleYear": "2018"
}
