@WebHost = http://localhost:5238

### Create Rule
POST {{WebHost}}/rules
Content-Type: application/json

{
  "Name": "BaseVehicleId",
  "Criteria": {
    "Items": [
      {
        "Field": "input1.VehicleId",
        "Operator": "Equal",
        "Value": "100"
      },
      {
        "Field": "input1.VehicleId",
        "Operator": "Equal",
        "Value": "200"
      }
    ],
    "CriteriaOperator": "Or"
  },
  "IsActive": true
}

### Update Rule
PUT {{WebHost}}/rules
Content-Type: application/json

{
  "Id": "5",
  "Name": "BaseVehicleId",
  "Criteria": {
    "Items": [
      {
        "Field": "input1.VehicleId",
        "Operator": "Equal",
        "Value": "100"
      },
      {
        "Field": "input1.VehicleId",
        "Operator": "Equal",
        "Value": "200"
      },
      {
        "Field": "input1.VehicleId",
        "Operator": "Equal",
        "Value": "300"
      }
    ],
    "CriteriaOperator": "Or"
  },
  "IsActive": true
}

### Get Rule by ID
GET {{WebHost}}/rules/1

### Get All Rules
GET {{WebHost}}/rules

### Delete Rule
DELETE {{WebHost}}/rules/4